<script setup lang="ts">
  import { computed } from 'vue';

  const props = defineProps<{
    status: string;
    questionId: number;
    generatedBy: string;
    createdAt: string;
  }>();

  const statusClasses = computed(() => {
    const status = props.status.toLowerCase();

    return {
      waiting: status.includes('waiting'),
      drafting: status.includes('draft'),
      rejected: status.includes('reject'),
      approved: status.includes('approve'),
    };
  });
</script>

<template>
  <div class="question-status-card" :class="statusClasses">
    <div class="status-grid">
      <div class="status-item">
        <label>Status</label>
        <h3>{{ status }}</h3>
      </div>

      <div class="status-item">
        <label>Question Id</label>
        <h3>{{ questionId }}</h3>
      </div>

      <div class="status-item">
        <label>Generated By</label>
        <h3>{{ generatedBy }}</h3>
      </div>

      <div class="status-item">
        <label>Created At</label>
        <h3>{{ createdAt }}</h3>
      </div>
    </div>
  </div>
</template>

